version: '3'

services:
  web:
    container_name: web-whatsnew-tg-bot
    build:
      context: ./app
    expose:
      - 8000
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - ./app/.env
    depends_on:
      - db
    networks:
      - whatsnew-tg-bot
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000"

  nginx:
    container_name: nginx-whatsnew-tg-bot
    image: nginx:latest
    ports:
      - ${NGINX_PORT:-8000}:8000
    depends_on:
      - web
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - whatsnew-tg-bot

  db:
    container_name: db-whatsnew-tg-bot
    image: postgres:14-alpine
    env_file:
      - .env.db
    expose:
      - 5432
    ports:
      - ${POSTGRES_PORT:-5435}:5432
    networks:
      - whatsnew-tg-bot
    volumes:
      - postgres-data-local:/var/lib/postgresql/data/

  redis:
    container_name: redis-whatsnew-tg-bot
    image: redis:latest
    expose:
      - 6379
    networks:
      - whatsnew-tg-bot
    volumes:
      - redis-data-local:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30

  celery:
    container_name: celery-whatsnew-tg-bot
    build:
      context: ./app
    command: celery -A config.celery worker -B --loglevel=debug
    volumes:
      - ./app/:/usr/src/app/
    depends_on:
      - web
    networks:
      - whatsnew-tg-bot

volumes:
  postgres-data-local:
  redis-data-local:


networks:
  whatsnew-tg-bot:
    driver: bridge

